package com.heartbeets.sharing

import com.heartbeets.audio.AffirmationSet
import com.heartbeets.audio.BinauralPreset
import com.heartbeets.audio.NoiseType
import com.heartbeets.audio.SolfeggioFrequency
import com.heartbeets.audio.SynthParams

/**
 * Live heartbeat data stored at /heartbeats/{code} in Firebase RTDB.
 * Each user has one permanent code; they toggle live/offline status.
 */
data class HeartbeatLive(
    val bpm: Int = 0,
    val updatedAt: Long = 0L,
    val status: String = STATUS_OFFLINE,
    val profileId: String = "",
) {
    companion object {
        const val STATUS_LIVE = "live"
        const val STATUS_OFFLINE = "offline"
    }
}

/**
 * A shared sound profile stored in Firestore under /profiles/{id}.
 * Contains the synth parameters needed to recreate the heartbeat sound.
 */
data class SharedProfile(
    val id: String = "",
    val name: String = "",
    val version: Int = 1,
    val createdBy: String = "",
    val synthParams: SynthParamsDto = SynthParamsDto(),
    // Background noise & binaural
    val noiseType: String = "NONE",
    val noiseVolume: Double = 0.1,
    val binauralPreset: String = "NONE",
    val binauralCarrierHz: Double = 200.0,
    val binauralBeatHz: Double = 10.0,
    val binauralVolume: Double = 0.3,
    // Solfeggio tone
    val solfeggioFrequency: String = "NONE",
    val solfeggioVolume: Double = 0.3,
    // Affirmations
    val affirmationSet: String = "NONE",
    val affirmationCustomTexts: List<String> = emptyList(),
    val affirmationIntervalSec: Int = 30,
    val affirmationVolume: Double = 0.8,
    val affirmationSpeechRate: Double = 0.9,
    val affirmationPitch: Double = 1.0,
)

/**
 * A friend entry stored locally. Maps a display name to their permanent code.
 */
data class Friend(
    val code: String,
    val name: String,
)

/**
 * A HeartCode is a sharing code generated by the user.
 * Each user can have multiple codes, each shared with specific friends.
 * Only enabled codes broadcast live status + BPM when the user goes live.
 */
data class HeartCode(
    val code: String,
    val name: String,
    val enabled: Boolean = true,
)

/**
 * DTO for [SynthParams] suitable for Firestore serialization.
 */
data class SynthParamsDto(
    val lubFrequency: Double = 65.0,
    val lubAmplitude: Double = 1.0,
    val lubDurationMs: Int = 80,
    val lubAttackMs: Int = 5,
    val lubDecayMs: Int = 60,
    val dubFrequency: Double = 95.0,
    val dubAmplitude: Double = 0.6,
    val dubDurationMs: Int = 60,
    val dubAttackMs: Int = 5,
    val dubDecayMs: Int = 45,
    val dubOffsetMs: Int = 150,
    val bodyFrequency: Double = 35.0,
    val bodyAmplitude: Double = 0.3,
    val bodyDurationMs: Int = 100,
    val lowPassHz: Double = 0.0,
    val noiseAmplitude: Double = 0.02,
    val masterGain: Double = 0.9,
) {
    fun toSynthParams(): SynthParams = SynthParams(
        lubFrequency = lubFrequency.toFloat(),
        lubAmplitude = lubAmplitude.toFloat(),
        lubDurationMs = lubDurationMs,
        lubAttackMs = lubAttackMs,
        lubDecayMs = lubDecayMs,
        dubFrequency = dubFrequency.toFloat(),
        dubAmplitude = dubAmplitude.toFloat(),
        dubDurationMs = dubDurationMs,
        dubAttackMs = dubAttackMs,
        dubDecayMs = dubDecayMs,
        dubOffsetMs = dubOffsetMs,
        bodyFrequency = bodyFrequency.toFloat(),
        bodyAmplitude = bodyAmplitude.toFloat(),
        bodyDurationMs = bodyDurationMs,
        lowPassHz = lowPassHz.toFloat(),
        noiseAmplitude = noiseAmplitude.toFloat(),
        masterGain = masterGain.toFloat(),
    )

    companion object {
        fun from(params: SynthParams): SynthParamsDto = SynthParamsDto(
            lubFrequency = params.lubFrequency.toDouble(),
            lubAmplitude = params.lubAmplitude.toDouble(),
            lubDurationMs = params.lubDurationMs,
            lubAttackMs = params.lubAttackMs,
            lubDecayMs = params.lubDecayMs,
            dubFrequency = params.dubFrequency.toDouble(),
            dubAmplitude = params.dubAmplitude.toDouble(),
            dubDurationMs = params.dubDurationMs,
            dubAttackMs = params.dubAttackMs,
            dubDecayMs = params.dubDecayMs,
            dubOffsetMs = params.dubOffsetMs,
            bodyFrequency = params.bodyFrequency.toDouble(),
            bodyAmplitude = params.bodyAmplitude.toDouble(),
            bodyDurationMs = params.bodyDurationMs,
            lowPassHz = params.lowPassHz.toDouble(),
            noiseAmplitude = params.noiseAmplitude.toDouble(),
            masterGain = params.masterGain.toDouble(),
        )
    }
}
